import React,{useEffect,useState} from 'react';
import {Routes,Route,Navigate,NavLink,useNavigate} from 'react-router-dom';
import Dashboard from './pages/Dashboard';
import Exams from './pages/Exams';
import Syllabus from './pages/Syllabus';
import Resources from './pages/Resources';
import Mistakes from './pages/Mistakes';
import Mocks from './pages/Mocks';
import Updates from './pages/Updates';
import Settings from './pages/Settings';
import {getState,updateState} from './store';

async function hash(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function Unlock({onUnlock}){const [pin,setPin]=useState('');const [setup,setSetup]=useState(!getState().settings.pinHash);const [error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');if(pin.length<4){setError('Use at least 4 characters.');return}const h=await hash(pin);const s=getState();if(setup){updateState({settings:{...s.settings,pinHash:h}});onUnlock(true)}else if(h===s.settings.pinHash){onUnlock(true)}else setError('Incorrect local PIN.');};return <div className="lock"><div className="lock-card"><div className="brand-mark">SC</div><h1>Study Command Center</h1><p>{setup?'Create a local PIN for this browser.':'Unlock your personal study dashboard.'}</p><form onSubmit={submit}><input autoFocus type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder={setup?'Create PIN':'Enter PIN'}/><button className="primary">{setup?'Create & continue':'Unlock'}</button></form>{error&&<div className="error">{error}</div>}<small>Your study data stays in this browser. This is a convenience lock, not server-side security.</small></div></div>}
function Layout({onLock}){const nav=useNavigate();const [now,setNow]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[]);const links=[['/','Today','◉'],['/exams','Exams','▣'],['/syllabus','Syllabus','☷'],['/resources','Resources','↗'],['/mistakes','Mistakes','!'],['/mocks','Mocks','✓'],['/settings','Settings','⚙']];return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">SC</div><div><b>Study Command</b><span>Center</span></div></div><nav>{links.map(([to,label,icon])=><NavLink key={to} to={to} className={({isActive})=>isActive?'active':''}><span>{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-bottom"><div className="mini-label">TODAY</div><b>{now.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</b><span>{now.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span><button onClick={()=>{onLock();nav('/')}} className="ghost">Lock app</button></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">PERSONAL STUDY OS</div><h2>{now.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</h2></div><button className="date-pill" onClick={()=>nav('/')}>Today <span>⌘K</span></button></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/exams" element={<Exams/>}/><Route path="/syllabus" element={<Syllabus/>}/><Route path="/resources" element={<Resources/>}/><Route path="/mistakes" element={<Mistakes/>}/><Route path="/mocks" element={<Mocks/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main></div>}
export default function App(){const [auth,setAuth]=useState(()=>sessionStorage.getItem('study-unlocked')==='1');const [ready,setReady]=useState(false);useEffect(()=>{setReady(true)},[]);const unlock=v=>{setAuth(v);if(v)sessionStorage.setItem('study-unlocked','1');};const lock=()=>{sessionStorage.removeItem('study-unlocked');setAuth(false)};if(!ready)return <div className="loading">Loading your study system…</div>;return auth?<Layout onLock={lock}/>:<Unlock onUnlock={unlock}/>}
